use super::ast::{ASTNode, AbstractSyntaxTree};
pub mod barracuda_pest_semantic_analyser;
pub mod scope_tracker;

/// The semantic analyser adds type annotations to the AST generated by the parser.
pub trait SemanticAnalyser {
    /// Creates a default configuration of an SemanticAnalyser
    fn default() -> Self;

    /// Analyse an Abstract Syntax Tree and annotate it with types.
    fn analyse(self, root_node: ASTNode, env_vars: EnvironmentSymbolContext) -> AbstractSyntaxTree;
}

// Concrete Definition Export
pub use self::barracuda_pest_semantic_analyser::BarracudaSemanticAnalyser;
pub use super::ast::EnvironmentSymbolContext;
